server:
  port: 8990
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: sign_route
          uri: lb://sign
          predicates:
            - Path=/sign/**

        - id: user_route
          uri: lb://user
          predicates:
            - Path=/user/**

        - id: queue_route
          uri: lb://queue
          predicates:
            - Path=/queue/**

        - id: point_route
          uri: lb://point
          predicates:
            - Path=/point/**
